### ISSUE TITLE
Choose doc docx to txt converter and call from backend

### ISSUE THREAD

**Issue by dzmitry-lahoda** [legalhackersby/chaintrack#1]
- LiberOffice from command line?
- pdf?

**Comment by dzmitry-lahoda** [comment]
https://tika.apache.org/

**Comment by Anufriev** [comment]
https://github.com/OfficeDev/Open-XML-SDK

**Comment by dzmitry-lahoda** [comment]
https://github.com/dagwieers/unoconv/issues/340

**Comment by dzmitry-lahoda** [comment]
Trying to plug it into C#.
